sudo: enabled
os: osx
language: c

install:
- git clone https://github.com/cc65/cc65 /tmp/cc65 &&
  sudo make -C /tmp/cc65 ca65 ld65 avail &&
  ca65 --version

script:
- make

before_deploy:
- git clone https://github.com/mach-kernel/cadius /tmp/cadius &&
  make -C /tmp/cadius
- cd $TRAVIS_BUILD_DIR/ &&
  CADIUS="/tmp/cadius/bin/release/cadius" res/package.sh

deploy:
  provider: releases
  prerelease: true
  api_key:
    secure: GKESS8qxyVM+0LHVniDMIKLi3ACVXQnacUvzEb/Qn+1PEw6aJ43mv4CQ8E8WyDXSi6i0FXgf72ky+bqa5u/ziYLAwgbtyu3MibNYl2Ryx8B/jdUCQsUPPlf75uBRgQNPt8gj9oBfRFh5omhZdNRaX3VHCYqi1ZrbAO3e2nunhfwddwcMLjl8wnzaM1jdm46lfdvt++GeihqCycdKVOpc6GZQqwwVtrHt9315JCzPJ9BXALxaQL0QSCpJ5uQwVhTS0Sh/k+VqxZ/nUyJ5sqgOulBRHwE0bgqKPV6zrnqftCr1PNwRXkOJfY3eM7ZbWr/vH8TaKU/21fSOxr3NmK/mHqiDun5Sm4duIRl+fm9QAxH93uyxsqPeAmxxSfNnvq6G0k3zFXPiRVgy1ceSIvYFZyCjKQEg0FF+vup0NzP85k8TpX3G4CO/WTOwVvnXruomMO5XpR3bnF1TIffDkU4DGtSpCO7FXH/Kq/CVQw3k155DhXE3IsHCId3bxlFnP0YHk/MS6Unzmcc4DDQS8pIgQII7woMv3g8gYiRQvp4gHbNvDbVi0kyAlJYbQ9lvOWjoFYs+sfxKG6J7AgO4CJ0c10/GwitvzGw9CUeR2O2sgX3i4DUbQEDCKgOO8rj+DqNH70ZtwJZmGG1TZfv1Og+hdoz9rLaFXGw1iFJ5/OXsLK8=
  file:
    - $TRAVIS_BUILD_DIR/out/A2DeskTop.po
    - $TRAVIS_BUILD_DIR/out/A2DeskTop.1.po
    - $TRAVIS_BUILD_DIR/out/A2DeskTop.2.po
    - $TRAVIS_BUILD_DIR/res/README.txt
  skip_cleanup: true
  on:
    repo: inexorabletash/a2d
    tags: true
